version: '1.0'

services:
  web:
    container_name: news
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/news'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    tty: true
    develop:
      watch:
        - action: sync
          path: .
          target: /news
        - action: rebuild
          path: package.json